name: Hawk
main: me.islandscout.hawk.Hawk
version: BETA 2006 (DEV)
author: Islandscout
description: An anticheat system
website: https://github.com/HawkAnticheat/Hawk
softdepend: [ProtocolLib]
commands:
    hawk:
        description: Basic information about Hawk Anticheat
        usage: /<command>
permissions:
  hawk.admin:
    description: Allows one to be considered an administrator to Hawk
    default: op
  hawk.cmd:
    description: Allows one to access help menu and GUI
    default: op
  hawk.cmd.*:
    description: Allows one to perform any Hawk command
    default: op
    children:
      hawk.cmd: true
  hawk.notify:
    description: Allows one to recieve Hawk notifications
    default: op
